### ISSUE TITLE
fatal error: wasmedge/wasmedge.h: No such file or directory

### ISSUE THREAD

**Issue by vlkv** [second-state/WasmEdge-go-examples#11]
Hello,

I am trying to run this example https://wasmedge.org/book/en/sdk/go/memory.html#pass-strings-to-tinygo-functions
with go1.19.3 linux/amd64

I wrapped the code in unit test, got error when trying to run it:
```
vitvlkv@emc2:~/tp/backend/indicators/tpi_worker/junk$ go test ./run_wasmedge/
# github.com/second-state/WasmEdge-go/wasmedge
/home/vitvlkv/go/pkg/mod/github.com/second-state/!wasm!edge-go@v0.11.2/wasmedge/ast.go:3:11: fatal error: wasmedge/wasmedge.h: No such file or directory
    3 | // #include <wasmedge/wasmedge.h>
      |           ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
FAIL    gitlab.takeprofit.team/backend/indicators/tpi_worker/junk/run_wasmedge [build failed]
FAIL
```

**Comment by hydai** [comment]
Hi @vlkv 
Have you installed wasmedge before using the wasmedge-go SDK?
Ref: https://wasmedge.org/book/en/sdk/go.html#getting-started

**Comment by vlkv** [comment]
My bad, I just did the 'go get ...'  thing. I am sorry, and thank you for the URL))

**Comment by hydai** [comment]
Thank you for confirming this. Maybe we should have a troubleshooting page for these problems. There must be some unclear part in our document, making you miss something :-(.

**Comment by vlkv** [comment]
I don't think your documentation have problems here. Everything about installation is documented very good. It was my fault that I did not read it. Sorry again and thank you for help)
