### ISSUE TITLE
Run example get fatal error: 'wasmedge.h' file not found

### ISSUE THREAD

**Issue by Taction** [second-state/WasmEdge-go-examples#2]
After run
```
$ cd go_ExternRef
$ go get -u github.com/second-state/WasmEdge-go
$ go build
```
I got follwing error:
```
# github.com/second-state/WasmEdge-go/wasmedge
/Users/zc/go/pkg/mod/github.com/second-state/!wasm!edge-go@v0.8.2/wasmedge/ast.go:3:11: fatal error: 'wasmedge.h' file not found
 #include <wasmedge.h>
          ^~~~~~~~~~~~
1 error generated.
```
I am using `go version go1.17.2 darwin/amd64`.

**Comment by q82419** [comment]
Hi @Taction ,

Please try to download and extract the `darwin` release of WasmEdge:

```
wget https://github.com/WasmEdge/WasmEdge/releases/download/0.8.2/WasmEdge-0.8.2-darwin_x86_64.tar.gz
tar zxvf WasmEdge-0.8.2-darwin_x86_64.tar.gz
```

And copy or move the header `WasmEdge-0.8.2-Darwin/include/wasmedge.h` to your header path (such as `/usr/local/include`),
And copy or move the library `WasmEdge-0.8.2-Darwin/lib/libwasmedge_c.dylib` to your library path (such as `/usr/local/lib`).

We are preparing for the `0.9.0` release of `WasmEdge-go`, and will update all installation guide to use the installer in the WasmEdge project.
Sorry for the current complicated usage.

Thanks.
